---
- name: Build and run Docker container
  hosts: docker_server
  gather_facts: no
  tasks:
    - name: Copy Dockerfile to the target machine
      copy:
        src: /home/kennllave/docker/dockerfile
        dest: /tmp/Dockerfile
      become: yes

    - name: Build Docker container
      command: "docker build -t web-db -f /tmp/Dockerfile /tmp"
      become: yes

